# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "282f1f8009056ec09d3047caedfaa5cf"
name = "order-rating"
application_url = "https://vegas-adding-ace-floors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sandbox-plus-sdi-y1-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://vegas-adding-ace-floors.trycloudflare.com/auth/callback",
  "https://vegas-adding-ace-floors.trycloudflare.com/auth/shopify/callback",
  "https://vegas-adding-ace-floors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
